### ISSUE TITLE
Support for parent tickets / custom fields

### ISSUE THREAD

**Issue by dennisoehme** [lesstif/php-jira-rest-client#16] opened 2015-10-18 18:46 UTC
Do you plan to bind custom fields from the REST response to objects or access the parent ticket?

**Comment by lesstif** [comment] 2015-10-19 04:23
to bind custom fields is difficulty features and i have no plan at this time.
i'm hoping to you contributing here. :)

**Comment by MBBanfi** [comment] 2015-10-26 09:25
It seems that it is possible to dynamically create attribute, and it is sent properly right now:
$issueField = new IssueField();
$issueField->customfield_10360 = 'XXX';

Of course the problem is validating field. Maybe having metadata of field could allow to create set of methods to create proper attribute, for example:

$issueField->addCustomField(mixed $fieldData, array $fieldSchema);

Where $fieldSchema is for example:
Array
(
    [required] => 
    [schema] => Array
        (
            [type] => string
            [custom] => com.atlassian.jira.plugin.system.customfieldtypes:textarea
            [customId] => 10360
        )

    [name] => Acceptance Criteria
    [hasDefaultValue] => 
    [operations] => Array
        (
            [0] => set
        )

)

Where based on type we can make validation and proper parameter type, and based on customId we can create parameter name.

Do you think it is good idea? If yes then I can create methods as I need custom fields to work and send it to you, so you could add it to the project if you feel it is worthy.

**Comment by nidup** [comment] 2016-02-17 11:22
@lesstif @MBBanfi any progress on this topic? I'm interested too, btw, thank you for the lib!

**Comment by lesstif** [comment] 2016-02-22 07:31
really sorry for delayed reply.

i think bind custom fields would be a useful features, but there is no progress yet.

**Comment by vagovszky** [comment] 2016-04-18 11:47
@lesstif cweiske/jsonmapper introduces mapping of "Unknown properties". It can be helpful for you. 
```
/**
 * Handle undefined properties during JsonMapper::map()
 *
 * @param object $object    Object that is being filled
 * @param string $propName  Name of the unknown JSON property
 * @param mixed  $jsonValue JSON value of the property
 *
 * @return void
 */
function setUndefinedProperty($object, $propName, $jsonValue)
{
    $object->{'UNDEF' . $propName} = $jsonValue;
}

$jm = new JsonMapper();
$jm->undefinedPropertyHandler = 'setUndefinedProperty';
$jm->map(...);
```

**Comment by lesstif** [comment] 2016-04-19 04:12
@vagovszky thanks for your comment. i have a plan to implements custom field at next week.

**Comment by Setitch** [comment] 2016-04-27 09:16
Lessif - as i wrote before i fixed a bit your library (sorry for so long time before i published it).
It also allows you to set/fetch custom fields. Feel free to use any code there^^

https://github.com/Setitch/php-jira-rest-client

**Comment by lesstif** [comment] 2016-04-28 11:14
@Setitch i can't access your repository. can you make the PR, please?

**Comment by Setitch** [comment] 2016-04-29 18:51
https://github.com/Setitch/php-jira-api-rest-client

I wrote the address wrongly - fixed it now. Sorry for that.

**Comment by lesstif** [comment] 2016-11-22 02:18
closed in https://github.com/lesstif/php-jira-rest-client/releases/tag/1.9.0.

**Closed** 2016-11-22 02:18 UTC
